{
 "title": "Unleash",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "quantile", "label": "Quantile", "query": "0.5, 0.9, 0.95, 0.99" }
  ]
 },
 "panels": [
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Availibility",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_milliseconds_count{status=~\"2.*|3.*\"}[1m])) / sum(rate(http_request_duration_milliseconds_count{}[1m])) * 100",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Request Rate per Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_milliseconds_count[1m])) by (endpoint,method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "HTTP Request Count per Path",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_milliseconds_count[1m])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "HTTP Request per Method per Path",
   "type": "timeseries",
   "description": "http_request_duration_milliseconds App response time",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "http_request_duration_milliseconds{quantile=\"$quantile\"}",
     "legendFormat": "{{method}}-{{path}} "
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Database Query Latency",
   "type": "timeseries",
   "description": "db_query_duration_seconds DB query duration time",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(db_query_duration_seconds) by  (store,action)",
     "legendFormat": "{{store}} {{action}} {{quantile}}"
    }
   ]
  },
  {
   "title": "Unleash DB Rate per Action per Store",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(db_query_duration_seconds_count{}[1m])) by (action,store)",
     "legendFormat": "{{action}}-{{store}}"
    }
   ]
  },
  { "title": "Database Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "db_pool_min",
   "type": "timeseries",
   "description": "Minimum DB pool size",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 51 },
   "targets": [
    { "expr": "sum(db_pool_min)/3", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "db_pool_max",
   "type": "timeseries",
   "description": "Maximum DB pool size",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 51 },
   "targets": [
    { "expr": "sum(db_pool_max)/3", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "db_pool_free",
   "type": "timeseries",
   "description": "Current free connections in DB pool",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 51 },
   "targets": [
    { "expr": "sum(db_pool_free)/3", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "db_pool",
   "type": "timeseries",
   "description": "Current connections in use in DB pool",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 51 },
   "targets": [
    { "expr": "sum(db_pool_used)/3", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "db_pool_pending_creates",
   "type": "timeseries",
   "description": "how many asynchronous create calls are running in DB pool",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 51 },
   "targets": [
    { "expr": "sum(db_pool_pending_creates)/3", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "db_pool_pending_acquires",
   "type": "timeseries",
   "description": "how many acquires are waiting for a resource to be released in DB pool",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 51 },
   "targets": [
    {
     "expr": "sum(db_pool_pending_acquires)/3",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Feature Toggle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Feature Toggle Updates",
   "type": "timeseries",
   "description": "feature_toggle_update_total Number of times a toggle has been updated. Environment label would be \"n/a\" when it is not available, e.g. when a feature toggle is created.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "avg(feature_toggle_update_total) by (toggle)",
     "legendFormat": "toggle:{{toggle}}   environment:{{environment}}"
    }
   ]
  },
  {
   "title": "Feature Toggle Usage",
   "type": "timeseries",
   "description": "feature_toggle_usage_total Number of times a feature toggle has been used",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "sum(rate(feature_toggle_usage_total[1m])) by (toggle)",
     "legendFormat": "toggle:{{toggle}}   environment:{{environment}}   active:{{active}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Number of Feature Toggles",
   "type": "stat",
   "description": "feature_toggles_total Number of feature toggles",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(feature_toggles_total{})", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Users",
   "type": "piechart",
   "description": "users_total Number of users",
   "gridPos": { "h": 8, "w": 5, "x": 2, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(users_total)/3", "legendFormat": "users total" },
    { "expr": "sum(users_active_7)/3", "legendFormat": "users active for 7 days" },
    { "expr": "sum(users_active_30)/3", "legendFormat": "users active for 1 month" },
    { "expr": "sum(users_active_60)/3", "legendFormat": "users active for 2 month" },
    { "expr": "sum(users_active_90)/3", "legendFormat": "users_active for 3 month" }
   ]
  },
  {
   "title": "Number of Strategies",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 7, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(strategies_total) ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Production Changes",
   "type": "stat",
   "description": "production_changes_30 Changes made to production environment last 30 days",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(production_changes_30)/3", "legendFormat": "production changes in 1 month" },
    { "expr": "sum(production_changes_60)/3", "legendFormat": "production changes in 2 month" },
    { "expr": "sum(production_changes_90)/3", "legendFormat": "production changes in 3 month" }
   ]
  },
  {
   "title": "Number of Projects",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(projects_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Environments",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(environments_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Configured Rate Limit",
   "type": "bargauge",
   "description": "ate_limits Rate limits (per minute) for METHOD/ENDPOINT pairs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate_limits) by (exported_endpoint,method)",
     "legendFormat": "endpoint: {{exported_endpoint}}   method: {{method}}"
    }
   ]
  },
  {
   "title": "Unleash Clients Info",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(client_sdk_versions) by (sdk_name,sdk_version)",
     "legendFormat": "{{sdk_name}}-{{sdk_version}}"
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Node.js Info",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nodejs_version_info) by (version,patch,major,minor)"
    }
   ]
  },
  {
   "title": "Max Open File Descriptors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_max_fds{job=\"unleash\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "process_open_fds{job=\"unleash\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Virtual Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"unleash\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Resident Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"unleash\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_heap_bytes", "legendFormat": "{{pod}}" }
   ]
  }
 ]
}